[package]
name = "highlights"
version = "1.0.0"
authors = ["Benjamin Scherer <ThatsNoMoon.Alderaan@gmail.com>"]
repository = "https://github.com/ThatsNoMoon/highlights"
license = "OSL-3.0"
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = ["macros", "blocking", "time", "fs"] }
rusqlite = { version = "0.24", features = ["bundled", "backup"] }
r2d2 = "0.8"
r2d2_sqlite = "0.17"
once_cell = "1.4"
regex = "1.3"
chrono = "0.4"
indoc = "1.0"
log = { version = "0.4", features = ["std", "serde"] }
simplelog = "0.9"
prometheus = "0.11"
hyper = "0.13"
serde = { version = "1", features = ["derive"] }
config = { version = "0.10", default-features = false, features = ["toml"] }
url = { version = "2.2", features = ["serde"] }
anyhow = "1.0.37"

[dependencies.serenity]
git = "https://github.com/serenity-rs/serenity"
branch = "current"
default-features = false
features = [
    "builder",
    "cache",
    "client",
    "collector",
    "gateway",
    "http",
    "model",
    "rustls_backend",
]

[dependencies.reqwest]
version = "0.10"
default-features = false
features = ["blocking", "rustls-tls"]
