[package]
name = "highlights"
version = "1.1.0-beta.0"
authors = ["ThatsNoMoon <git@thatsnomoon.dev>"]
repository = "https://github.com/ThatsNoMoon/highlights"
license = "OSL-3.0"
edition = "2018"

[features]
default = ["dashboard"]
bot = [
    "regex",
    "indoc",
    "serenity/builder",
    "serenity/cache",
    "serenity/client",
    "serenity/collector",
    "serenity/gateway",
    "serenity/http"
]
monitoring = ["prometheus", "hyper"]
reporting = ["reqwest", "url"]
dashboard = [
    "warp",
    "http",
    "base64",
    "serde_json",
    "uuid",
    "dashmap",
    "cookie",
    "time",
    "url",
    "reqwest"
]

[dependencies]
tokio = { version = "1.0", features = ["macros", "rt", "rt-multi-thread", "time", "fs"] }
rusqlite = { version = "0.25", features = ["bundled", "backup"] }
r2d2 = "0.8"
r2d2_sqlite = "0.18"
once_cell = "1.4"
regex = { version = "1.3", optional = true }
chrono = "0.4"
indoc = { version = "1.0", optional = true }
log = { version = "0.4", features = ["std", "serde"] }
simplelog = "0.10"
prometheus = { version = "0.12", optional = true }
hyper = { version = "0.14", features = ["server"], optional = true }
warp = { version = "0.3", features = ["tls"], optional = true }
http = { version = "0.2", optional = true }
base64 = { version = "0.13", optional = true }
serde_json = { version = "1.0", optional = true }
uuid = { version = "0.8", features = ["v4", "serde"], optional = true }
dashmap =  { version = "4.0", optional = true }
cookie = { version = "0.15", optional = true }
time = { version = "0.2", optional = true }
serde = { version = "1.0", features = ["derive"] }
config = { version = "0.11", default-features = false, features = ["toml"] }
url = { version = "2.2", features = ["serde"], optional = true }
anyhow = "1.0"
futures-util = "0.3"

[dependencies.serenity]
version = "0.10"
default-features = false
features = ["model", "rustls_backend"]

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["blocking", "rustls-tls", "json"]
optional = true
